# Top 50 cryptocurrencies optimized for $100 account
TOP_50_MICRO = [
    'BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'XRPUSDT',
    'ADAUSDT', 'AVAXUSDT', 'DOTUSDT', 'DOGEUSDT', 'MATICUSDT',
    'LTCUSDT', 'TRXUSDT', 'LINKUSDT', 'ATOMUSDT', 'XMRUSDT',
    'ETCUSDT', 'XLMUSDT', 'BCHUSDT', 'FILUSDT', 'APTUSDT',
    'ARBUSDT', 'NEARUSDT', 'VETUSDT', 'ALGOUSDT', 'ICPUSDT',
    'EOSUSDT', 'AAVEUSDT', 'XTZUSDT', 'NEOUSDT', 'STXUSDT',
    'THETAUSDT', 'SANDUSDT', 'AXSUSDT', 'KLAYUSDT', 'RUNEUSDT',
    'FTMUSDT', 'MANAUSDT', 'GALAUSDT', 'CRVUSDT', 'KAVAUSDT',
    'GRTUSDT', 'CHZUSDT', 'ZILUSDT', 'COMPUSDT', 'SNXUSDT',
    'EGLDUSDT', 'QTUMUSDT', 'IOSTUSDT', 'ONTUSDT', 'IOTAUSDT'
]

SYMBOL_CATEGORIES = {
    'high_volume': ['BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'XRPUSDT'],
    'medium_volume': ['ADAUSDT', 'AVAXUSDT', 'DOTUSDT', 'MATICUSDT', 'LTCUSDT'],
    'low_volume_high_vol': ['DOGEUSDT', 'TRXUSDT', 'XLMUSDT', 'VETUSDT', 'GALAUSDT']
}

PRICE_TIERS = {
    'under_1': ['DOGEUSDT', 'TRXUSDT', 'XLMUSDT', 'VETUSDT'],
    '1_10': ['ADAUSDT', 'MATICUSDT', 'LTCUSDT', 'XRPUSDT'],
    '10_100': ['SOLUSDT', 'DOTUSDT', 'AVAXUSDT', 'LINKUSDT'],
    'over_100': ['BTCUSDT', 'ETHUSDT', 'BNBUSDT']
}